In [2]:
def loadDataset():
    """
    :return: 词条集合;类别标签
    """
    postingList=[
        ["my","dog","has","flea","problems","help","please"],
        ["maybe","not","take","him","to","dog","park","stupid"],
        ["my","dalmation","is","so","cute","I","love","him"],
        ["stop","posting","stupid","worthless","garbage",],
        ["mr","licks","ate","my","steak","how","to","stop","him"],
        ["quit","buying","worthless","dog","food","stupid"]
    ]

    classVec=[0,1,0,1,0,1]
    return postingList,classVec

In [3]:
def createVocabList(dataset):
    """
    :param dataset: 数据集
    :return: 不重复词的列表
    """
    vocabSet=set([])
    for document in dataset:
        vocabSet=vocabSet|set(document)
    return list(vocabSet)

In [4]:
def setOfWords2Vec(vocabList,inputSet):
    """
    :param vocabList: 词汇表
    :param inputSet: 输入文档
    :return: 文档向量(向量每个元素为1或0)
    """
    returnVec=[0]*len(vocabList)
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)]=1
        else:
            print("The word:%s is not in my Vocabulary!"%word)
    return returnVec

In [5]:
listOPosts,listClasses=loadDataset()

In [6]:
myVocabList=createVocabList(listOPosts)

In [7]:
myVocabList

['stupid',
 'worthless',
 'garbage',
 'help',
 'dog',
 'maybe',
 'love',
 'problems',
 'dalmation',
 'food',
 'buying',
 'quit',
 'posting',
 'stop',
 'ate',
 'mr',
 'him',
 'has',
 'so',
 'licks',
 'steak',
 'flea',
 'park',
 'my',
 'not',
 'to',
 'is',
 'take',
 'I',
 'cute',
 'how',
 'please']

In [8]:
setOfWords2Vec(myVocabList,listOPosts[0])

[0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [9]:
from numpy import *

In [10]:
def trainNB0(trainMatrix,trainCategory):
    numTrainDocs=len(trainMatrix)
    numWords=len(trainMatrix[0])
    pAbusive=sum(trainCategory)/float(numTrainDocs)
    p0Num=zeros(numWords)
    p1Num=zeros(numWords)
    p0Denom=0.0
    p1Denom=0.0
    for i in range(numTrainDocs):
        if trainCategory[i]==1:
            p1Num+=trainMatrix[i]
            p1Denom+=sum(trainMatrix[i])
        else:
            p0Num+=trainMatrix[i]
            p0Denom+=sum(trainMatrix[i])
    p1Vect=p1Num/p1Denom
    p0Vect=p0Num/p0Denom
    return p0Vect,p1Vect,pAbusive

In [11]:
trainMat=[]

for postinDoc in listOPosts:
    trainMat.append(setOfWords2Vec(myVocabList,postinDoc))

In [12]:
p0V,p1V,pAb=trainNB0(trainMat,listClasses)

In [13]:
pAb

0.5

In [14]:
p0V

array([0.        , 0.        , 0.        , 0.04166667, 0.04166667,
       0.        , 0.04166667, 0.04166667, 0.04166667, 0.        ,
       0.        , 0.        , 0.        , 0.04166667, 0.04166667,
       0.04166667, 0.08333333, 0.04166667, 0.04166667, 0.04166667,
       0.04166667, 0.04166667, 0.        , 0.125     , 0.        ,
       0.04166667, 0.04166667, 0.        , 0.04166667, 0.04166667,
       0.04166667, 0.04166667])

In [15]:
p1V

array([0.15789474, 0.10526316, 0.05263158, 0.        , 0.10526316,
       0.05263158, 0.        , 0.        , 0.        , 0.05263158,
       0.05263158, 0.05263158, 0.05263158, 0.05263158, 0.        ,
       0.        , 0.05263158, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05263158, 0.        , 0.05263158,
       0.05263158, 0.        , 0.05263158, 0.        , 0.        ,
       0.        , 0.        ])

改进算法

In [16]:
def trainNB0Improve(trainMatrix,trainCategory):
    numTrainDocs=len(trainMatrix)
    numWords=len(trainMatrix[0])
    pAbusive=sum(trainCategory)/float(numTrainDocs)
    p0Num=ones(numWords)
    p1Num=ones(numWords)
    p0Denom=2.0
    p1Denom=2.0
    for i in range(numTrainDocs):
        if trainCategory[i]==1:
            p1Num+=trainMatrix[i]
            p1Denom+=sum(trainMatrix[i])
        else:
            p0Num+=trainMatrix[i]
            p0Denom+=sum(trainMatrix[i])
    p1Vect=log(p1Num/p1Denom)
    p0Vect=log(p0Num/p0Denom)
    return p0Vect,p1Vect,pAbusive

In [17]:
trainMat=[]

for postinDoc in listOPosts:
    trainMat.append(setOfWords2Vec(myVocabList,postinDoc))

In [18]:
p0V,p1V,pAb=trainNB0Improve(trainMat,listClasses)

In [19]:
pAb

0.5

In [20]:
p0V

array([-3.25809654, -3.25809654, -3.25809654, -2.56494936, -2.56494936,
       -3.25809654, -2.56494936, -2.56494936, -2.56494936, -3.25809654,
       -3.25809654, -3.25809654, -3.25809654, -2.56494936, -2.56494936,
       -2.56494936, -2.15948425, -2.56494936, -2.56494936, -2.56494936,
       -2.56494936, -2.56494936, -3.25809654, -1.87180218, -3.25809654,
       -2.56494936, -2.56494936, -3.25809654, -2.56494936, -2.56494936,
       -2.56494936, -2.56494936])

In [21]:
p1V

array([-1.65822808, -1.94591015, -2.35137526, -3.04452244, -1.94591015,
       -2.35137526, -3.04452244, -3.04452244, -3.04452244, -2.35137526,
       -2.35137526, -2.35137526, -2.35137526, -2.35137526, -3.04452244,
       -3.04452244, -2.35137526, -3.04452244, -3.04452244, -3.04452244,
       -3.04452244, -3.04452244, -2.35137526, -3.04452244, -2.35137526,
       -2.35137526, -3.04452244, -2.35137526, -3.04452244, -3.04452244,
       -3.04452244, -3.04452244])

In [22]:
def classifyNB(vec2Classify,p0Vec,p1Vec,pClass1):
    p1=sum(vec2Classify*p1Vec)+log(pClass1)
    p0=sum(vec2Classify*p0Vec)+log(1.0-pClass1)
    
    if p1>p0:
        return 1
    else:
        return 0

In [23]:
def testingNB():
    listOPosts,listClasses=loadDataset()
    myVocabList=createVocabList(listOPosts)
    trainMat=[]
    for postinDoc in listOPosts:
        trainMat.append(setOfWords2Vec(myVocabList,postinDoc))
    p0V,p1V,pAb=trainNB0(array(trainMat),array(listClasses))
    testEntry=["love","my","dalmation"]
    thisDoc=array(setOfWords2Vec(myVocabList,testEntry))
    print(testEntry,"classified as:",classifyNB(thisDoc,p0V,p1V,pAb))
    testEntry=["stupid","garbage"]
    thisDoc=array(setOfWords2Vec(myVocabList,testEntry))
    print(testEntry,"classified as:",classifyNB(thisDoc,p0V,p1V,pAb))

In [24]:
testingNB()

['love', 'my', 'dalmation'] classified as: 0
['stupid', 'garbage'] classified as: 1


In [25]:
def bagOfWords2VecMN(vocabList,inputSet):
    returnVec=[0]*len(vocabList)
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)]+=1
    return returnVec

## 六.朴素贝叶斯：过滤垃圾邮件

In [26]:
mySent="This book is best book on Python or M.L I have ever laid eyes upon."

In [27]:
mySent.split()

['This',
 'book',
 'is',
 'best',
 'book',
 'on',
 'Python',
 'or',
 'M.L',
 'I',
 'have',
 'ever',
 'laid',
 'eyes',
 'upon.']

In [38]:
import re

regEx=re.compile('\\W')

listOfTokens=regEx.split(mySent)

listOfTokens

['This',
 'book',
 'is',
 'best',
 'book',
 'on',
 'Python',
 'or',
 'M',
 'L',
 'I',
 'have',
 'ever',
 'laid',
 'eyes',
 'upon',
 '']

In [39]:
[tok for tok in listOfTokens if len(tok)>0]

['This',
 'book',
 'is',
 'best',
 'book',
 'on',
 'Python',
 'or',
 'M',
 'L',
 'I',
 'have',
 'ever',
 'laid',
 'eyes',
 'upon']

In [40]:
[tok.lower() for tok in listOfTokens if len(tok)>0]

['this',
 'book',
 'is',
 'best',
 'book',
 'on',
 'python',
 'or',
 'm',
 'l',
 'i',
 'have',
 'ever',
 'laid',
 'eyes',
 'upon']

In [41]:
[tok.upper() for tok in listOfTokens if len(tok)>0]

['THIS',
 'BOOK',
 'IS',
 'BEST',
 'BOOK',
 'ON',
 'PYTHON',
 'OR',
 'M',
 'L',
 'I',
 'HAVE',
 'EVER',
 'LAID',
 'EYES',
 'UPON']

In [42]:
emailText=open("./data/email/ham/6.txt").read()

listOfTokens=regEx.split(emailText)

In [43]:
listOfTokens

['Hello',
 '',
 '',
 'Since',
 'you',
 'are',
 'an',
 'owner',
 'of',
 'at',
 'least',
 'one',
 'Google',
 'Groups',
 'group',
 'that',
 'uses',
 'the',
 'customized',
 'welcome',
 'message',
 '',
 'pages',
 'or',
 'files',
 '',
 'we',
 'are',
 'writing',
 'to',
 'inform',
 'you',
 'that',
 'we',
 'will',
 'no',
 'longer',
 'be',
 'supporting',
 'these',
 'features',
 'starting',
 'February',
 '2011',
 '',
 'We',
 'made',
 'this',
 'decision',
 'so',
 'that',
 'we',
 'can',
 'focus',
 'on',
 'improving',
 'the',
 'core',
 'functionalities',
 'of',
 'Google',
 'Groups',
 '',
 '',
 '',
 'mailing',
 'lists',
 'and',
 'forum',
 'discussions',
 '',
 '',
 'Instead',
 'of',
 'these',
 'features',
 '',
 'we',
 'encourage',
 'you',
 'to',
 'use',
 'products',
 'that',
 'are',
 'designed',
 'specifically',
 'for',
 'file',
 'storage',
 'and',
 'page',
 'creation',
 '',
 'such',
 'as',
 'Google',
 'Docs',
 'and',
 'Google',
 'Sites',
 '',
 '',
 'For',
 'example',
 '',
 'you',
 'can',
 'easily',
 

In [49]:
def textParse(bigstring):
    """
    :param bigstring: 大字符串
    :return: 字符串列表
    """
    import re

    listOfTokens=re.split(r"\W",bigstring)
    return [tok.lower() for tok in listOfTokens if len(tok)>2]

In [80]:
def spamText():
    """
    :return: 错误百分比
    """
    import random

    docList=[]
    classList=[]
    fullText=[]

    for i in range(1,26):
        wordList=textParse(open("./data/email/spam/%d.txt"%i).read())
        docList.append(wordList)
        fullText.extend(wordList)
        classList.append(1)

        wordList=textParse(open("./data/email/ham/%d.txt"%i,"rt",encoding="latin-1").read())
        docList.append(wordList)
        fullText.extend(wordList)
        classList.append(0)

    vocabList=createVocabList(docList)
    trainingSet=list(range(50))
    testSet=[]

    for i in range(10):
        randIndex=int(random.uniform(0,len(trainingSet)))
        testSet.append(trainingSet[randIndex])
        del(trainingSet[randIndex])

    trainMat=[]
    trainClasses=[]

    for docIndex in trainingSet:
        trainMat.append(setOfWords2Vec(vocabList,docList[docIndex]))
        trainClasses.append(classList[docIndex])

    p0V,p1V,pSpam=trainNB0(array(trainMat),array(trainClasses))
    errorCount=0

    for docIndex in testSet:
        wordVector=setOfWords2Vec(vocabList,docList[docIndex])
        if classifyNB(array(wordVector),p0V,p1V,pSpam)!=classList[docIndex]:
            errorCount+=1

    print("The error rate is:",float(errorCount)/len(testSet))

In [106]:
spamText()
spamText()

The error rate is: 0.6
The error rate is: 0.1


In [110]:
import feedparser

ny=feedparser.parse("http://newyork.craigslist.org/stp/index.xss")

In [111]:
len(ny["entries"])

0